### ISSUE TITLE
Program does not show buttons when Windows text is magnified to 175%

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#1]
Great program Brandon! I have been recommending it [in this Microsoft Community thread regarding Microsoft Word errors: "Unspecified Error, word/document.xml, Line:2, Column: 0"](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_other/unspecified-error-worddocumentxml-line2-column-0/21971fa0-df44-4ba6-ac42-7d4b5cd4174f?page=58&msgId=a5147334-955b-4929-9366-6f5a65a0764c).

I have a big monitor and my eyes are having "senior" problems so in the "Customize your display" section of  System settings of PC settings, I set "Change the size of text, apps and other items: 175%." 
![image](https://user-images.githubusercontent.com/885414/27486478-b696b536-57fe-11e7-82c4-e70ee166d453.png)

When I do this, wordcorruptdocchecker in the new Github releases, v1.2.0.4 and v.1.2.0.5 don't magnify proportionally for me. Instead the right side of the software Window with the buttons, is cut off. I do not have this problem with the Codeplex version and when I change the magnification to 100%, the problem goes away.
![image](https://user-images.githubusercontent.com/885414/27486662-4ff3d290-57ff-11e7-9a2b-0b95707e6611.png)

Here's what I see with the Codeplex version even at 175%:
![image](https://user-images.githubusercontent.com/885414/27486713-75eb5694-57ff-11e7-9461-ab5e6781062a.png)

**Comment by desjarlais** [comment]
Thanks for the report socrtwo, I'll work on getting it fixed soon.

**Comment by socrtwo** [comment]
Sounds good.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.


On Wed, Aug 2, 2017 at 1:09 AM, Brandon Desjarlais <notifications@github.com

**Comment by desjarlais** [comment]
I was able to reproduce the issue you described.  Made some changes and now the app should do a better job of scaling in v1.2.0.8.  Give it a try and let me know if you still see any problems.

**Comment by desjarlais** [comment]
If you still see the problem in v1.2.0.8, re-open this issue and I'll keep looking into it.  Closing for now.

**Comment by socrtwo** [comment]
​​Brandon,

Your v1.2.0.8 version works fine now at 175% zoom on the display fonts for
Windows 10.

I was able to get the program to fix these seven files
<https://drive.google.com/file/d/0B4rG1uoXTSmyVGdDVzFJVW1LN0k/view?usp=sharing>.​
Two others
<https://drive.google.com/file/d/0B4rG1uoXTSmyZ2c3VVlVNkVoWjVJQ3ZPY182N2oxbUhaLTNN/view?usp=sharing>,
were reported fixed by Word Corrupt Document Checker v1.2.0.8, but Word
2016 refused to open.

If you are interested, starting with your interface and some of the code
from my S2 Recovery Tools for Microsoft Word
<https://sourceforge.net/projects/wordrecovery/> SourceForge project (and
other Microsoft Word Repair projects I have on Sourceforge as well), I'm
making a new version my program as a kind of fork of your project, using
your code for those files that have out of order tags and similar XML
problems. I don't know how to use GitHub to do a fork that is a kind of
hybrid of two projects correctly...

My program really tries to be a comprehensive project that in addition to
offering quick repair like Word Corrupt Document Checker, tries to offer
programmatically every way of repair suggested by my article in the link
below including the usually ineffective advice offered by Microsoft itself
and including links to every commercial program I could find, good articles
on the subject and videos. Here's the link to that blog article that I'm
trying to turn into a one big crazy program:
https://free-data-recovery.blogspot.com/2016/03/this-is-cross-post-from-answer-i-made.html
.

I think the program is almost done except for programmatically being able
to carry out two of the ten or so different suggestions for corrupt Word
files that *will* open. Also I have to transfer your new code to the
appropriate out of order tag section of my code. I used the code from your
CodePlex version of Word Corrupt Document Checker as the code stands
presently. Some of my code in general also doesn't work correctly though
the approach might be right. Additionally there isn't a lot of commenting.
Also since I'm not a professional programmer I repeat things a lot which
should be modularized although there is some modularity and nods to good
programming basics.

I also have to fix the ability to look for previous versions of the file
automatically if System Protection is turned on and add code for recovering
older versions of files from Microsoft's new way of keeping backup copies
is implemented.

Here is a link from Sourceforge to the code as it stands now:
https://sourceforge.net/projects/wordrecovery/files/Version%203.0.2-alpha-source.zip/download.
I didn't work on the program for about a year or year and half or two years
and just got back into it as inspired by your answering my bug fix request.

I have about 200 corrupt zip files that include the 9 that your program
agreed had bad XML that it could fix. If I remember correctly all the files
can be fixed either programmatically or manually. If I remember right I
have only about 5-10 that I can't fix programmatically but can still be
done manually. By fixing I mean opening in Word even if the document is so
damaged that is severely truncated.

The one I was still having problems with, are in the "Unspecified" error
folder. They too should be able to be fixed programmatically if they can be
done manually, which they can be. I don't know if the present state of my
code will work on most of the files. The error messages that Word 2016
gives are of course different from earlier versions and I used the error
messages from earlier versions to determine which algorithm to use with the
file during "Quick Repair."

Anyway here is a link
<https://drive.google.com/file/d/0B4rG1uoXTSmyLW5ONzJid3lLMTA/view?usp=sharing>
to the files. I run a small file repair service and have been doing so for
15 years, so I have some files...:

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.


On Fri, Aug 4, 2017 at 1:33 AM, Brandon Desjarlais <notifications@github.com

**Comment by desjarlais** [comment]
Thanks for the additional details and I would agree the comments aren't exactly as helpful as they could be. 
 When I get time I'll go back and see what can be done there.  As for the program and files, was there something you wanted specific help with in the code or with the files?  If so, you could open another issue and mention what you are looking for and I'll do what I can to help.

**Comment by socrtwo** [comment]
Brandon,

OK will do.

I opened a new bug request. With one of the two files I have that Word
Corrupt Doc Checker says it fixed, but won't open in Word 2016, EXPO
SISTEMAS.docx
<https://drive.google.com/file/d/0B4rG1uoXTSmyZUQwemRFY2RRNEl3VzZLWV91RUtMaGlwR2Vj/view?usp=sharing>
(shared
on my Google drive), at moment, this is what your program does:

Invalid Tag: </w:txbxContent></w:pict></mc:Fallback></mc:AlternateContent>
Replaced With: </w:txbxContent></v:textbox></v:shape></w:pict></mc:Fallback
></mc:AlternateContent>
-------------------------------------------------------------
Fixed Document Location: D:\Paul D Pruitt\Desktop\EXPO SISTEMAS(Fixed).docx

If a </v:rect> tag is substituted for the </v:shape> in the same position,
the file does open.

I formally asked for a bug fix, but the file is not mine but a client's,
and I'm not sure if it becomes public if I attach it to the request.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.


On Tue, Aug 8, 2017 at 6:35 PM, Brandon Desjarlais <notifications@github.com

**Comment by socrtwo** [comment]
This problem has reoccurred with version: v1.2.1.8. See: [https://1drv.ms/i/s!AtqwKV_OsClkg9M-Q3TkLNx1nj8gzA](https://1drv.ms/i/s!AtqwKV_OsClkg9M-Q3TkLNx1nj8gzA). It pretty much looks the same as when the problem was occurring previously.
