### ISSUE TITLE
When Word Corrupt Doc Checker Finds the Document Does Not Contain Invalid XML...

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#3]
When Word Corrupt Doc Checker finds that a document does not contain invalid XML, it also marks the target document as being inaccessible because it being in use, leading to a possibly false hope that releasing the file from another program might allow it to be fixed.

For example here is a recent error message from a file that the program says doesn't have invalid:

` This document does not contain invalid xml.`
`ERROR: The process cannot access the file 'D:\Paul D Pruitt\Desktop\corrupt_docx_files\Unspecified error\math_tags\Japanese_characters_file(Fixed).docx' because it is being used by another process.`

**Comment by desjarlais** [comment]
Do you have a file to share that can reproduce this behavior?

**Comment by desjarlais** [comment]
Actually, you don't need to share a file.  This was something I noticed after releasing 1.2.0.8 and I've fixed it in a recent update, I just haven't had a chance to push the exe to the releases location.  

I'll be adding version 1.2.1.3 soon and it should prevent that incorrect logging statement to the UI.

**Comment by desjarlais** [comment]
I'll close the issue, but I do appreciate the reports.  Feel free to open any other issues you find and I'll do what I can to fix them.
