### ISSUE TITLE
Suggestion: Add a Info-Zip Zip Pretreament for Repairing the Zip Structure of the DOCX

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#4]
Suggestion: Add a pretreatment step for repairing the zip structure of the DOCX with [InfoZip's Zip](http://www.info-zip.org/Zip.html) command line app. I have found that among the free command line zip program, it is the best at repairing corrupt zip structure.

**Comment by desjarlais** [comment]
I'll need to research this idea a little more.  I'd like to avoid taking any dependency that is not directly on a default install of Windows.  Right now I'm using the .NET framework packaging library to pull out the files from the zip file container and if I could stay in there, it would be ideal, I haven't researched it or InfoZip's repair capability for a zip file so I'll have to circle back on this after doing some investigation.

**Comment by socrtwo** [comment]
I wonder if there any zip repair functionality in the .NET framework.That
would be cool and interesting if there were. I'll look into it myself.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
Hey Paul, I've been looking into this and I think I'm going to pass on this and maybe come back to this later, but for now I'm going to close this issue as Won't Fix until I can find a better library that isn't an external library and re-open at that point.  Thanks again for all of the suggestions, I do appreciate the effort.

**Comment by socrtwo** [comment]
OK, no problem. I think it's useful to do a zip repair pretreatment and I
don't think it damages the DOCX, but you obviously make the decisions. Most
of the DOCX repair apps I coded, see:
https://sourceforge.net/u/socrtwo22/profile/, do have this prestep, so it
is available for people to try. My apps are mostly on Sourceforge at the
moment.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.
