### ISSUE TITLE
If the Program Claims to Have Repaired Bad XML and the File Still Won't Open Offer to Remove Fallback Tags

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#7]
If the Word Corrupt Doc Checker is able to fix bad XML and the program is unsuccessful at opening the file in a new instance of Word, show a pop up Windows which both explains what Fallback tags are and offers to remove them.

**Comment by desjarlais** [comment]
The challenge here is knowing the instance of Word failed to open the file.  I do like the idea though, so I'll have to think this through a bit and figure out what works best.

**Comment by socrtwo** [comment]
In my current project, I use a try and catch set where the try is an
attempt to open the possibly repaired file, however you can tell Word to
not make the application window visible and you can also tell it to go
straight into Open and Repair mode. Of course when the attempt fails, you
go to the catch section and can open a message box with a choice there. You
can also kill the hidden instance of Word there too.

Here is my I'm sure crappy coding:

​I've set this up top:

using Application = Microsoft.Office.Interop.Word.Application;​


​Then here is the rest:​


try
> ​​
>

{
> var strDestPath = Path.GetDirectoryName(strOrigFileName) + @"\";
> var strExtension = Path.GetExtension(strOrigFileName);
> var strDestFileName = strDestPath +
>
Path.GetFileNameWithoutExtension(strOrigFileName) + "_fixed" + strExtension;

var strDestFileNameWithQuotes = @"""" + strDestFileName
> ​​
> + @"""";
> var strDestFileNameWithQuotesAndDoubleSlashes =
>
strDestFileNameWithQuotes.Replace(@"\", @"\\");
>
var wordWithoutRepairDialogAndNotVisibleApp =
> new Application { Visible = false };
> wordWithoutRepairDialogAndNotVisibleApp.Documents.OpenNoRepairDialog(
>
strDestFileNameWithQuotesAndDoubleSlashes, OpenAndRepair: true);

if (wordWithoutRepairDialogAndNotVisibleApp.ProtectedViewWindows.Count > 0)
> {
> wordWithoutRepairDialogAndNotVisibleApp.ActiveProtectedViewWindow.Edit();
> }
> }
> catch
> {
> *​//​Open a message box​ with a choice and whatever choice is taken, do
> more stuff within //the catch statement​*


​You can also do this here so the hidden Word instance doesn't keep hanging
around:

KillProcess(@"WINWORD");​

}


Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
Thanks for the sharing the code and I do appreciate all the feedback you've been posting.  I could pull in the interop and automate the Word application, but I would like to avoid all the extra work needed to handle automating the winword executable.  I'll probably start with the Open Xml SDK first and go from there.

**Comment by desjarlais** [comment]
I've added the open xml sdk check, if it can't open there, it still has invalid xml and an additional logging comment was added to let the user know to try the remove fallback option.

**Comment by socrtwo** [comment]
Very nice. So you are validating with Open XML SDK?

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
Correct.
