### ISSUE TITLE
Change the Name of the Project to the More Grammatically Correct "Corrupt Word DOCX Checker"

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#8]
Word Corrupt DOC Checker sounds clumsy. This is probably because adjectives need to follow a certain order, see: http://www.gingersoftware.com/content/grammar-rules/adjectives/order-of-adjectives/[http://www.gingersoftware.com/content/grammar-rules/adjectives/order-of-adjectives/](url). Here "Corrupt" is a quality (#2 on the list), which should be in front of "Word" which is a proper adjective (#7) which properly precedes I think "DOC" which I think is a purpose or qualifier (#8 in the list order).

If the program can only work with DOCX files, the program should replace DOC with DOCX. If it works with other variants like the macro enable DOCM files, perhaps the long form, "Document" should be reintroduced, but this may be a matter of taste.

Finally Microsoft has grammar guidelines which say that when referring to Word, see: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/publications.aspx[https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/publications.aspx](url). This sentence "You may not:
use the Marks as the leading word or most prominent element in your publication, seminar, or conference title;" may be applicable to "Word Corrupt DOC Checker" which starts with "Word" clearly referring to "Microsoft Word" as its leading word.

**Comment by desjarlais** [comment]
I could probably use either of these:

1. Corrupt Word DOCX Checker
2. Corrupt Word Document Checker
3. Corrupt Word Document (DOCX) Checker

You are correct, the existing name is very clumsy.  I'll keep this open and workshop this a little while and see if I can come up with a better name.  I'm leaning towards 2, but I like the idea of explicitly calling out it only works for the open xml format document.

**Comment by socrtwo** [comment]
You could use Corrupt Word DOCX Document Checker without the parenthesis.
Any of them is fine. You could expand the scope and include DOC text
salvaging using this command line app:
http://silvercoders.com/en/products/doctotext/. That's what I did in
several iterations of my corrupt Word document salvaging/fixing programs.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
I'll use "Corrupt Word Document Checker" for now and we can revisit later if this should be amended to include the "DOCX" qualifier.  Thanks for the suggestions!

**Comment by socrtwo** [comment]
Happy to help.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.
